mode: train
dataset_code: amazon

# amazon_url: https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/categoryFiles/AMAZON_FASHION.json.gz
amazon_url: https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/categoryFiles/Movies_and_TV.json.gz
# amazon_metadata_url: https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/metaFiles2/meta_AMAZON_FASHION.json.gz
amazon_metadata_url: https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/metaFiles2/meta_Movies_and_TV.json.gz

model_code: bert
dataloader_code: bert
trainer_code: bert
use_hard_negative_mining: false
use_prefix_augmentation: false
experiment_description: "bert_test_from_script"
device: cuda
num_gpu: 1
min_rating: 0
min_uc: 5
min_sc: 0
split: leave_one_out
train_batch_size: 128
val_batch_size: 128
test_batch_size: 128
train_negative_sampler_code: random
train_negative_sample_size: 0
train_negative_sampling_seed: 0
test_negative_sampler_code: random
test_negative_sample_size: 100
test_negative_sampling_seed: 98765
optimizer: Adam
lr: 0.001
enable_lr_schedule: false
decay_step: 30
gamma: 1.0
num_epochs: 1
metric_ks: [1, 5, 10, 20, 50, 100]
best_metric: "NDCG@10"
model_init_seed: 0
bert_dropout: 0.1
bert_hidden_units: 256
bert_mask_prob: 0.15
bert_max_len: 100
bert_num_blocks: 2
bert_num_heads: 4
recreate_data: false
do_test: true